### ISSUE TITLE
No have wifi 

### ISSUE THREAD

**Issue by minhngoc123** [r33int/Hackintosh-Dell-Latitude-E5440#2]
Can you send me wifi driver .i intall and don't have wifi

**Comment by nickbotr** [comment]
Are you using the same wifi card listed?

**Comment by Whatever-Green** [comment]
> Can you send me wifi driver .i intall and don't have wifi
Not all wifi cards are supported by mac OS, you could buy a wifi card that is supported or buy a wifi dongle.

**Comment by r33int** [comment]
You can now use itlwm to get Intel wifi to work: https://github.com/OpenIntelWireless/itlwm
